In [1]:
import numpy as np

### Rotation & Trasformation Matrix


In [2]:
R_x = lambda theta: np.array([[1,0,0], [0,np.cos(theta), -np.sin(theta)], [0,np.sin(theta), np.cos(theta)]])
R_y = lambda theta: np.array([[np.cos(theta), 0, np.sin(theta)], [0,1,0], [-np.sin(theta), 0, np.cos(theta)]])
R_z = lambda theta: np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta),0], [0,0,1]])
p = lambda x,y,z: np.array([x,y,z,1]).T

In [3]:
H = lambda R, p: np.array([[R[0][0], R[0][1], R[0][2], p[0]],
                           [R[1][0], R[1][1], R[1][2], p[1]],
                           [R[2][0], R[2][1], R[2][2], p[2]],
                           [0, 0, 0, 1]])

# 1. Scara Configuration RRP


In [4]:
def ScaraSolver(q1,q2,d,l0,l1,l2):
    """
    This fuction returns the p0
    
    
    
    's coordinates
    Keyword arguments:
    q1,q1 -- joint angles|d -- planar joint movement|l0,l1,l2 -- link lengths from base to planar joint
    Return: return a 4 X 1 vector with [p0x,p0y,p0z,1] configuration
    """
    H01 = H(R_z(np.deg2rad(q1)),p(0,0,l0))
    H12 = H(R_z(np.deg2rad(q2)), p(l1,0,0))
    H23 = H(R_y(np.deg2rad(90)), p(l2,0,0))
    p3 = p(d,0,0)
    return H01@H12@H23@p3

In [5]:
ans = ScaraSolver(30,45,2,5,4,3)

In [6]:
ans

array([4.24055875, 4.89777748, 3.        , 1.        ])

# 2. Stanford Configuration RRP


In [7]:
def StanfordSolver(q1,q2,d,l1,l2):
    """
    This fuction returns the p0's coordinates

    Keyword arguments:
    q1,q1 -- joint angles|d -- planar joint movement|l1,l2 -- link lengths from base to planar joint
    Return: return a 4 X 1 vector with [p0x,p0y,p0z,1] configuration
    """
    H01 = H(R_z(np.deg2rad(q1)), p(0,0,0))
    H12 = H(R_y(np.deg2rad(-90)),p(0,0,l1))
    H23 = H(R_z(np.deg2rad(q2)), p(0,0,0))
    H34 = H(R_z(np.deg2rad(0)), p(0,0,-l2))
    H45 = H(R_z(np.deg2rad(-90)), p(0,0,0))
    p5 = p(d,0,0)
    return H01@H12@H23@H34@H45@p5

In [12]:
StanfordSolver(30,45,3,5,5)

array([5.39078719, 0.66288269, 7.12132034, 1.        ])

# 3. Drone Obstacle


In [17]:
def drone():
    """
    This fuction returns the p0's coordinates

    Keyword arguments:
    q1,q1 -- joint angles|d -- planar joint movement|h -- drone height
    Return: return a 4 X 1 vector with [p0x,p0y,p0z,1] configuration
    """
    H01 = H(R_z(np.deg2rad(0)),(0,0,10))
    H12 = H(R_x(np.deg2rad(30)),(0,0,0))
    H23 = H(R_z(np.deg2rad(60)),(0,0,0))
    p3 = p(0,0,3)
    return H01@H12@H23@p3

In [18]:
drone()

array([ 0.        , -1.5       , 12.59807621,  1.        ])