# Jacobian

In [18]:
import numpy as np

In [40]:
l1 = 5
l2 = 4
l3 = 3
q1 = 45
q2 = 30
q3 = 60
h = 10
d= 6

c = lambda angle: np.cos(np.deg2rad(angle))
s = lambda angle: np.sin(np.deg2rad(angle))

In [41]:
Z_i = np.array([0,0,1]).T
j_v = lambda Z_i, O_i: np.cross(Z_i, (O_i)).T

## Jacobian for RRP Scara

In [55]:
Scara = np.array([[l1*c(q1), l1*s(q1), h], [l1*c(q1)+l2*c(q2), l1*s(q1)+l2*s(q2), h - d]]).T

In [56]:
Scara

array([[ 3.53553391,  6.99963552],
       [ 3.53553391,  5.53553391],
       [10.        ,  4.        ]])

In [61]:
J_v = np.array([j_v(Z_i, Scara[:,1]), j_v(Z_i, Scara[:,0]), -1*Z_i])

In [62]:
J_v

array([[-5.53553391,  6.99963552,  0.        ],
       [-3.53553391,  3.53553391,  0.        ],
       [ 0.        ,  0.        , -1.        ]])

In [63]:
J_w = np.array([Z_i,Z_i,np.zeros(3)]).T

In [64]:
J = np.vstack((J_v,J_w))

In [65]:
J

array([[-5.53553391,  6.99963552,  0.        ],
       [-3.53553391,  3.53553391,  0.        ],
       [ 0.        ,  0.        , -1.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.        ,  1.        ,  0.        ]])

## Jacobian for RRR planar

In [66]:
Planar3R = np.array([[l1*c(q1), l1*s(q1), 0], [l1*c(q1)+l2*c(q2), l1*s(q1)+l2*s(q2), 0],[l1*c(q1)+l2*c(q2)+l3*c(q3), l1*c(q1)+l2*c(q2)+l3*c(q3), 0]]).T

In [67]:
Planar3R

array([[3.53553391, 6.99963552, 8.49963552],
       [3.53553391, 5.53553391, 8.49963552],
       [0.        , 0.        , 0.        ]])

In [73]:
J_v_planar = np.array([j_v(Z_i, Planar3R[:,2]), j_v(Z_i, Planar3R[:,1]), j_v(Z_i, Planar3R[:,0])]).T

In [74]:
J_v_planar

array([[-8.49963552, -5.53553391, -3.53553391],
       [ 8.49963552,  6.99963552,  3.53553391],
       [ 0.        ,  0.        ,  0.        ]])

In [75]:
J_w_planar = np.array([Z_i,Z_i,Z_i]).T

In [76]:
J_planar = np.vstack((J_v_planar, J_w_planar))

In [77]:
J_planar

array([[-8.49963552, -5.53553391, -3.53553391],
       [ 8.49963552,  6.99963552,  3.53553391],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.        ,  1.        ,  1.        ]])